### PR TITLE
Windows improvements

### PR DESCRIPTION
**Pull request by jder**
Fixes two annoyances with using codalab from windows.

* Changes the name of a test file to not include characters which are invalid on windows (this makes even checking out the code break). Arguably we could do something to create a dynamic file based on operating system, but this is complicated. We could consider this after we merge with upstream.
* Removes the unnecessary call to `os.getppid()` which is unavailable on Windows, and have it recognize common windows shells.

### CODE REVIEW

**Review by percyliang — APPROVED** [review]

**Comment by percyliang** [comment]
Is there an easy way to push these upstream automatically even though the
two codalab-cli's are out of sync?

**Comment by jder** [comment]
Not that I know of, though we could write something. It’s not clear you’d want this change anyway? (The filename thing in particular)


________________________________

**Comment by percyliang** [comment]
Making things work in Windows seems like a good thing in general...

**Comment by jder** [comment]
@percyliang so, do you want me to put up a PR to upstream codalab with this?

**Comment by percyliang** [comment]
That'd be great, thanks.

**Comment by jder** [comment]
https://github.com/codalab/codalab-cli/pull/971

**Comment by percyliang** [comment]
Thanks!

**Pull request merged**
